/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello From lab03");
    }
}
