/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import com.sun.jdi.Value;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testingWeatherMethod(){
        int[][] givenArray = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        String[] result = {"High: 72", "Low: 51", "Never saw temperature: 63", "Never saw temperature: 67", "Never saw temperature: 68", "Never saw temperature: 69"};

       assertEquals(Arrays.toString(result), String.valueOf(Library.weather(givenArray)) );

    }
    @Test void testingVotingMethod() {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner = "Bush received the most votes!";
        assertEquals(winner, Library.tally(votes));
    }

}
